---
- hosts: planet
  tasks:
  - setup:
  - ec2_facts:

- hosts: '{{ hosts }}'
  vars:
    pgmaster_group_name: 'dc2-pgmaster'
    pgstandby_group_name: 'dc2-pgstandby'
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'ps'}
  - apigee-opdk-setup-postgresql-add

